// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:cb6d8253-7b75-42a3-91b3-04a0f9908cea",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_46PvLC9tZ",
    "aws_user_pools_web_client_id": "4valinv83h4ifa2grri6ffeqct",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "ap-southeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Txns-sharrenv",
            "region": "ap-southeast-2"
        }
    ]
};


export default awsmobile;
