// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:b83adcdc-daee-4e16-abbd-36be566b0ea8",
    "aws_cognito_region": "ap-southeast-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "321823b4d75c47d785b0874394c561a5",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
